name: First CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "*.py"
      - "requirements.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt
      - run: python app.py

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - run: pip install pytest
      - run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Fake Deploy
        run: echo "Deploying application..."
